run:
  tests: false
  timeout: 3m
  build-tags: []
  go: '1.22'
  allow-parallel-runners: true

output:
  format: tab
  sort-results: true

issues:
  max-issues-per-linter: 75
  max-same-issues: 5

linters:
  enable-all: false
  enable:
    - errcheck
    - govet
    - ineffassign
    - gomodguard
  disable:
    - revive
    - tagliatelle
    - nlreturn
    - maligned
    - varnamelen
    - scopelint
    - gochecknoinits
    - lll
    - interfacer
    - gochecknoglobals
    - typecheck
    - dupl
    - wsl
    - stylecheck
    - testpackage
    - golint
    - gosimple
    - bodyclose
    - contextcheck
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - tparallel
    - unparam
    - wastedassign
    - unused
    - deadcode
    - exhaustivestruct
    - nosnakecase
    - ifshort
    - varcheck
    - goimports
