postgres:
  host: localhost
  port: 6000
  user: vpbuyanov
  password: sevabuyanov
  dbname: gw

redis:
  host: localhost
  port: 6379
  password:
  DB: 0

server:
  port: 8080
  host: 127.0.0.1

JWT:
  secret: asd

mailer:
  name: info learnio
  from_email_address: info@learnio.space
  from_email_password: pifrzyidqyeyyucd