version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      gw:

  backend-go:
    image: vpbuyanov/gw-backend-go:latest
    container_name: gw-backend-go
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
      - .postgres.env
    depends_on:
      - postgres
    networks:
      gw:

volumes:
  postgres-data:

networks:
  gw: