services:
  postgres:
    image: postgres:latest
    container_name: gw-postgres
    restart: unless-stopped
    ports:
      - "6000:5432"
    env_file:
      - .postgres.env
    volumes:
      - gw-postgres-data:/var/lib/postgresql/data/pgdata
    networks:
      gw:

  redis:
    image: redis:latest
    container_name: gw-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - gw-redis-data:/data
    networks:
      gw:

  backend-go:
    image: vpbuyanov/gw-backend-go:latest
    container_name: gw-backend-go
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - gw-backend-go:/var/lib/server/data
      - ./config.yaml:/config.yaml
    depends_on:
      - postgres
    networks:
      gw:

volumes:
  gw-redis-data:
  gw-backend-go:
  gw-postgres-data:

networks:
  gw: