version: '3.9'

services:
  server:
    build: .
    image: buyanse/gw-backend-go:latest
    container_name: gw-backend-go
    ports:
      - "8080:8080"
    command: ["go", "run", "cmd", "migrate", "main.go"]
